name: 'Merge the release to develop'
run-name:  Merge the released `${{ github.head_ref }}` from `trunk` to `develop`

# **What it does**: Merges trunk to develop after `release/*` is merged to `trunk`.
# **Why we have it**: To automate the release process and follow git-flow.

on:
  pull_request:
    types:
      - closed
    branches:
      - trunk

jobs:
  automerge_trunk:
    name: Automerge released trunk
    runs-on: ubuntu-latest
    steps:
      - uses: woocommerce/grow/automerge-released-trunk@actions-v1
